### ISSUE TITLE
Issues with the URL [unknown url type: 'zwift_parser.py']

### ISSUE THREAD

**Issue by marcosimonegili** [alexshpunt/zwift_workout_parser#1]
I am having troubles with the positional argument (str) URLs. This is how I run the script:

- `zwift_parser.py [-ed ["C:\Users\DNC\Downloads"]] URLs [https://whatsonzwift.com/workouts/gravel-grinder]`
or
- `zwift_parser.py URLs "https://whatsonzwift.com/workouts/gravel-grinder" -ed "C:\Users\DNC\Downloads"`

And here is the output, having some issues with the URL:

![image](https://github.com/alexshpunt/zwift_workouts_parser/assets/29420400/4d8204e5-2ae3-4a31-8fce-82ebbb558374)

**Comment by alexshpunt** [comment]
Hi, thanks for notifying me, I'll try to check what is wrong with that.

**Comment by alexshpunt** [comment]
@marcosimonegili sorry that it took quite long for a relatively easy issue at the end, but as I haven't used the tool for a while now, so had to recollect how it actually works. But basically in order to fix your problem you should just use the next command: 

`zwift_parser.py "https://whatsonzwift.com/workouts/gravel-grinder" -ed "C:\Users\DNC\Downloads"`

I've updated the project config, so now it should install all the dependencies for the project as well. And I will update README, with some examples of usage, so it's clearer how it works. Thanks that you have raised the issue though!

**Comment by marcosimonegili** [comment]
> @marcosimonegili sorry that it took quite long for a relatively easy issue at the end, but as I haven't used the tool for a while now, so had to recollect how it actually works. But basically in order to fix your problem you should just use the next command:
> 
> `zwift_parser.py "https://whatsonzwift.com/workouts/gravel-grinder" -ed "C:\Users\DNC\Downloads"`
> 
> I've updated the project config, so now it should install all the dependencies for the project as well. And I will update README, with some examples of usage, so it's clearer how it works. Thanks that you have raised the issue though!

Thank you so much for getting back to me! I tried but something is still wrong with the URL parser: 

![image](https://github.com/alexshpunt/zwift_workouts_parser/assets/29420400/07221b5c-272f-4a87-bbe7-424f3158d06b)

![image](https://github.com/alexshpunt/zwift_workouts_parser/assets/29420400/de628185-70ab-4770-8e1c-69a45f2f1690)

**Comment by alexshpunt** [comment]
@marcosimonegili seems like you've added an extra \` character at the end of the URL to download. I've just checked and it's my fault, accidentally added it while switching from code style to code block in markdown. So check the updated README!. 
Also please set `$zwift_workouts_folder` to the folder where you want to store all the workouts, instead of default value which I provided with the readme. As it seems that your local is different from Eng and instead of Downloads it might be Descargas. 

By the way, there is an archive with all the exported workouts from the site, so you might find it useful as well, so check this out: https://github.com/alexshpunt/zwift_workouts_parser/releases/tag/Export. You should use either .zip or .tag.gz archive files.
